//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Details.Models
{
    using System;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;

    public partial class Login_SignUp_UserDetails
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "FirstName Required !")]
        public string First_Name { get; set; }

        [Required(ErrorMessage = "LastName Required !")]
        public string Last_Name { get; set; }

        [Required(ErrorMessage = "Gmail Required !")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}" +
                            @"\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\" +
                            @".)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$",
                            ErrorMessage = "Email is not valid")]
        public string Gmail_Id { get; set; }

        [Required(ErrorMessage = "UserName Required !")]
        public string User_Name { get; set; }

        [Required(ErrorMessage = "PassWord Required !")]
        public string PassWord { get; set; }
    }
}
