//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Details.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Student_Details_Sundram
    {

        public int Student_ID { get; set; }


       
        [Required(ErrorMessage = "Roll No Required !")]
        public int Student_Roll_Number { get; set; }


        
        [Required(ErrorMessage = "FirstName is required !")]
        public string Student_FirstName { get; set; }

        [Required(ErrorMessage = "LastName is required !")]
        public string Student_LastName { get; set; }


        [Required(ErrorMessage = "College Name Required !")]
      
        public string Student_UniversityName { get; set; }

        [Required(ErrorMessage = "Email is Requirde")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}" +
                            @"\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\" +
                            @".)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$",
                            ErrorMessage = "Email is not valid")]
        public string Student_MailId { get; set; }

        [Required(ErrorMessage = "P-Language Required !")]
       
        public string Student_Preffered_ProgrammingLanguage { get; set; }
    }
}
